### ISSUE TITLE
Pre-emptive libc version woe

### ISSUE THREAD

**Issue by itowlson** [fermyon/spin-cloud-gpu#7]
This project currently builds on `ubuntu-latest`.  In other projects, we've found this causes problems for folks on Debian or Ubuntu 20, because it causes a dependency on a later version of libc.  We should generally prefer to do builds on Ubuntu 20.04.

**Comment by karthik2804** [comment]
I agree with this but it has a dependency on `js2wasm` getting a release out as the action to install it will depend on `ubuntu-latest`.

**Comment by karthik2804** [comment]
closed by #10
